### ISSUE TITLE
Please. Share your modifications do the code

### ISSUE THREAD

**Issue by psicotron3** [RetroScaler/NGC-BlueRetro#3]
The compiled version is very old (1.7.3) compared with the official version.

We can use the oficcial version but the controller connection color leds will stop working.

Could please share the sourcecode with the changes made for the color leds to work?

**Comment by criptych** [comment]
The licensing here is confusing: this repo says GPL-3.0, which requires source distribution, except that this repo has no source code to distribute. Meanwhile the BlueRetro base linked in README is Apache-2.0, which doesn't, so technically RetroScaler is only violating their own license…?

FWIW, from inspection of the board it looks like the red/green/yellow/white player LEDs are connected to GPIO 14/32/33/25 respectively.

**Comment by rafaeoz** [comment]
> s

what version should I flash ?

**Comment by psicotron3** [comment]
> The licensing here is confusing: this repo says GPL-3.0, which requires source distribution, except that this repo has no source code to distribute. Meanwhile the BlueRetro base linked in README is Apache-2.0, which doesn't, so technically RetroScaler is only violating their own license…? (IANL.)
> 
> FWIW, from inspection of the board it looks like the red/green/yellow/white player LEDs are connected to GPIO 14/32/33/25 respectively.

It looks after version 1.7.3 darthcloud implemented led features. Looks like it's on system/manager.c.

But even if he implemented it the same way retroscaler did, the pins are different from what you found. And pins 32/33 are now used as SENSE_PIN.

I don't think it can be solved. But at least, the leds presence don't make it incompatible with newer firmwares.

**Comment by psicotron3** [comment]
I changed the SENSE_PIN lines on manager.c to match the ones that criptych found out (14/32/33/25) and compiled. The leds worked and until now, everything is working fine. 

I´ll ask darkcloud and if he doesn't care, I'll add those compiled binaries to may repo this weekend if nothing else breaks.

**Comment by darthcloud** [comment]
I'm quite annoyed by this TBH, as courtesy after seeing their preview tweet in September (and to avoid incompatibility with official FW) I sent them by email an earlier version of this HW2 schematic: https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-HW2-External-Specification#9---example-schematic-base-on-spec

They said nothing and in a subsequent email with them I reminded them to check the schematic.

I never got feedback from them and they asked me nothing either.

And now we got non-compliant HW in the wild.

If they used the schematic the product would have been much better as it wouldn't even require all the plug to be connected, and the BT controller would get assigned to the detected plug-in cable. (Like you could just plug cable #2 in port #1 and the first BT controller would get assign cable #2)

The right thing to do IMHO is to respin their PCB to be compliant to the BlueRetro spec (either HW1 or HW2 as the port LED is available on both FW)

**Comment by psicotron3** [comment]
In this case, supporting this hardware wont do any good.  Unfortunately I can't ask for a refund anymore, but I'll make sure to share the information that it's an unsupported, non-compliant, hardware and eventually it'll fade away.

**Comment by rafaeoz** [comment]
> In this case, supporting this hardware wont do any good. Unfortunately I can't ask for a refund anymore, but I'll make sure to share the information that it's an unsupported, non-compliant, hardware and eventually it'll fade away.

I'll be glad if you share . Maybe the last FW , don't have this bug I'm confronting.

**Comment by psicotron3** [comment]
Anyway, only changing SENSE_PIN lines on manager.c to match the ones that criptych found out made the leds work again but, as expected, introduced some random connection errors and sometimes button presses are lost. I'm not willing to investigate (to be honest, I don't think I would be able to solve).

Your best bet is to use the official releases from [darthcloud](https://github.com/darthcloud/BlueRetro/releases). Until now, they are working fine, with the drawback that the controller connection color leds will stop working.

**Comment by psicotron3** [comment]
I'll close this. Even without having access to code changes, it became clear that those changes can't be merged to official firmware.

**Comment by RetroScaler** [comment]
In fact, this is a different hardware from HW2, four indicator lights of different colors mainly indicate whether the wireless handle is connected successfully.
I just came back from holiday, and I will update the schematic diagram and source code within these two days,

**Comment by rafaeoz** [comment]
> In fact, this is a different hardware from HW2, four indicator lights of different colors mainly indicate whether the wireless handle is connected successfully.
> I just came back from holiday, and I will update the schematic diagram and source code within these two days,

If you can see if I can resolve my problem sycing more than 1 Dualshock 4 . 
I use a mapped profile  to merge both L and R digital and analog , from the official page from darkcloud. 
But just 1 of the Dualshock 4 work . The rest remais without the profile. And yes, I mapped all four outputs. 
And they work with other controllers I have like my Ds3 and a Ipega one.
