### ISSUE TITLE
Is there actually firmware for this?

### ISSUE THREAD

**Issue by Pro-man13** [RetroScaler/NGC-BlueRetro#5]
Yeah, I feel a bit dumb, but I did use the wrong firmware to flash this device. I've realized this now, but I can't actually find a ngc4p bin of any number at all in the files I can download. I am probably missing something obvious, so sorry in advance for a noob issue being asked.

**Comment by zinob** [comment]
I haven't ordered this product yet so i can't say if this works. But if you still have this problem there is a small "releases" topic labeled "releases"  on the right hand side of the projects main page. It leads to https://github.com/RetroScaler/NGC-BlueRetro/releases/tag/v1.8.3 (at the time of writing), you have a bin-file in the list of downloads.

**Comment by Pro-man13** [comment]
Thanks, not sure how I missed this. The last time I checked through the files I couldn't find any of the 4controllers bin files. Probably need to get my eyes checked or something.
